"""
Company Research UI Module
==========================

This module handles the PySide6 UI for manually validating and editing 
company research results in Phase 2.
"""

import sys
import json
from PySide6.QtWidgets import (QApplication, QDialog, QVBoxLayout, 
                               QHBoxLayout, QTextEdit, QPushButton, 
                               QLabel, QMessageBox)
from PySide6.QtGui import QFont

class TextEditorDialog(QDialog):
    """
    A dialog for editing JSON text with syntax validation.
    """
    def __init__(self, initial_text, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Company Research Validation")
        self.resize(800, 600)
        
        layout = QVBoxLayout(self)
        
        # Instructions
        label = QLabel("Please review the company mappings generated by Gemini.\n"
                       "Ensure dictionary format is correct and names are valid.\n"
                       "Click 'Accept' to proceed or 'Retry' to regenerate.")
        label.setFont(QFont("Arial", 10, QFont.Bold))
        layout.addWidget(label)

        # Editor
        self.editor = QTextEdit()
        self.editor.setPlainText(initial_text)
        self.editor.setFont(QFont("Consolas", 10))
        layout.addWidget(self.editor)

        # Buttons
        btn_layout = QHBoxLayout()
        
        self.btn_accept = QPushButton("Accept & Continue")
        self.btn_accept.clicked.connect(self.accept_text)
        self.btn_accept.setStyleSheet("background-color: #4CAF50; color: white; padding: 10px;")
        
        self.btn_retry = QPushButton("Retry Generation")
        self.btn_retry.clicked.connect(self.retry_action)
        self.btn_retry.setStyleSheet("background-color: #FF9800; color: white; padding: 10px;")
        
        self.btn_cancel = QPushButton("Cancel / Exit")
        self.btn_cancel.clicked.connect(self.reject)
        self.btn_cancel.setStyleSheet("background-color: #f44336; color: white; padding: 10px;")

        btn_layout.addWidget(self.btn_accept)
        btn_layout.addWidget(self.btn_retry)
        btn_layout.addWidget(self.btn_cancel)
        
        layout.addLayout(btn_layout)

        self.final_text = None
        self.status = "cancelled"

    def accept_text(self):
        text = self.editor.toPlainText()
        try:
            # Validate JSON
            json.loads(text)
            self.final_text = text
            self.status = "accepted"
            self.accept()
        except json.JSONDecodeError as e:
            QMessageBox.critical(self, "Invalid JSON", f"Error parsing JSON:\n{e}")

    def retry_action(self):
        self.status = "retry"
        self.accept()

    def run(self):
        """Helper to execute dialog and return status."""
        self.exec()
        return self.status, self.final_text

def run_ui_validation(initial_json: list) -> tuple[str, list]:
    """
    Launches the UI to validate the given JSON list.
    
    Returns:
        tuple: (status_string, validated_json_list)
        status_string: 'accepted', 'retry', or 'cancelled'
    """
    app = QApplication.instance() or QApplication(sys.argv)
    
    text_input = json.dumps(initial_json, indent=2)
    dialog = TextEditorDialog(text_input)
    status, final_text = dialog.run()
    
    if status == "accepted" and final_text:
        return status, json.loads(final_text)
    
    return status, None
